### ISSUE TITLE
RequestTimedOutError and AuthorizationError

### ISSUE THREAD

**Issue by jwalkerlusd** [jwalkerlusd/snmp-scout#1]
```sh
node cli.js --rules ./snmp-scout-rules.example.js
```
returned:

```sh
Error processing rule: RequestTimedOutError: Request timed out
    at Timeout.<anonymous> (.../snmp-scout/node_modules/net-snmp/index.js:2205:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[]
```

then after setting communities to real values, it returned:

```sh
Error processing rule: RequestFailedError: AuthorizationError
    at Req.Session.onSimpleGetResponse [as onResponse] (/home/admin/projects/snmp-scout/node_modules/net-snmp/index.js:2180:20)
    at Session.onMsg (/home/admin/projects/snmp-scout/node_modules/net-snmp/index.js:2163:7)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:930:8) {
  status: 16
}
[]
```

**Comment by jwalkerlusd** [comment]
Because this tool is for discovery, errors of these types are expected and can be safely ignored. However, the current revision quits at the first error.

- cli.js: should ignore these errors and continue
- snmp-scout.ts: should offer an .on("error", ...) callback
